# Gems
plugins:
  - jekyll-paginate-v2
  - jekyll-gist
  - redcarpet
safe: true
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate-v2
  - jekyll-gist
  - redcarpet

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           'pretty'
#relative_permalinks: true
# Rendering
markdown:            'kramdown'
highlighter:         'rouge'
# Setup
title:               'Ryan Bensussan Harvey'
tagline:             "Instructor in Computer Science <div class='social-icons'><a href='https://github.com/nihonjinrxs' target='_blank' alt='GitHub account'><i class='fa fa-github'> </i></a> <a href='https://twitter.com/CodeAndData' target='_blank' alt='Twitter account'><i class='fa fa-twitter'> </i></a> <a href='https://www.linkedin.com/in/ryanbharvey' target='_blank' alt='LinkedIn account'><i class='fa fa-linkedin-square'> </i></a> <a href='https://codeanddata.codes' target='_blank' alt='Professional website of Ryan B. Harvey'><i class='fa fa-globe'> </i></a></div>"
description:         "Information about Ryan's teaching, research and computer science education work."

pagination: 
  enabled: true
  per_page: 10

credits:             'Built with <a href="http://jekyllrb.com" target="_blank">Jekyll</a> and the <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon theme</a> by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# About/contact
author:
- name:              'Ryan Bensussan Harvey'
- url:               'https://people.loyno.edu/~rharvey'
- email:             'rharvey@loyno.edu'
# Custom vars
version:             '1.5.0'
github:
- repo:              'https://github.com/nihonjinrxs/loyno-faculty-repo'

# for development
# site_environment:    'development'

# for deploy only
site_environment:    'production'

# loyno.edu deploy
url:                 'https://loyno.edu/~rharvey'
baseurl:             '/~rharvey'
google_analytics:    'UA-211408-6'

# github pages deploy
# url:                 'http://codeanddata.codes/loyno-faculty-site'
# baseurl:             '/loyno-faculty-site'
# google_analytics:    'UA-211408-7'
